// vue-cli/Vue2/axiostest/github案例_vue-resource/components/Search.vue
<template>
  <div id="search">
      <a-input-search
      placeholder="input search text"
      enter-button="Search"
      size="large"
      @search="onSearch"
      v-model="value"
    />
  </div>
</template>

<script>
import axios from 'axios'
export default {
    name:'Search',
    data () {
        return {
            value:''
        }
    },
    methods: {
        onSearch(){
            this.$bus.$emit('updataListData',{isFirst:false,isLoad:true,errMsg:'',users:[]})
            this.$http.get(`https://api.github.com/search/users?q=${this.value}`).then(
                response => {
                    console.log(response.data.items);
                    this.$bus.$emit('updataListData',{isLoad:false,errMsg:'',users: response.data.items})
                },
                error => {
                    console.log(error.message)
                    this.$bus.$emit('updataListData',{isLoad:false,errMsg:error.message,users:[]})
                }
            )
        }
    }
}
</script>

<style scoped>
#search{
    width: 300px;
    margin: auto;
}
</style>

// React/React-Cli/01-hello/06-githun案例-消息的订阅与发布/components/Search/index.jsx
import React, { Component } from 'react'
import './index.css'
import axios from 'axios'
import pubsub from 'pubsub-js'

export default class index extends Component {
    search = () => {
        const { input: { value } } = this
        // this.props.updateAppState({isFirst:false, isLoading:true})
        pubsub.publish('user', { isFirst: false, isLoading: true })
        axios.get(`https://api.github.com/search/users?q=${value}`).then(
            response => {
                // this.props.updateAppState({isLoading:false, users:response.data.items})
                pubsub.publish('user', { isLoading: false, users: response.data.items })
            },
            error => {
                // this.props.updateAppState({isLoading:false, err:error.message});
                pubsub.publish('user', { isLoading: false, err: error.message })
            }
        )
    }
    render() {
        return (
            <div id='search'>
                <h1>搜索github用户</h1>
                <input ref={currentNode => this.input = currentNode} placeholder="请输入搜索关键词" type="text" />
                <button onClick={this.search}>搜索</button>
            </div>
        )
    }
}
