// vue-cli/Vue2/axiostest/求和案例_多组件共享数据/components/Person.vue
<template>
  <div>
    <h1>人员列表</h1>
    <h2>Count组件求和：{{sum}}</h2>
    <input type="text" placeholder="请输入名字" v-model="name">
    <button @click="add">添加</button>
    <ul>
      <li v-for="p in personlist" :key="p.id">{{ p.name }}</li>
    </ul>
  </div>
</template>

<script>
import nanoid from 'nanoid'

export default {
  name: 'Person',
  data() {
    return {
      name: ''
    }
  },
  computed: {
    personlist() {
      return this.$store.state.personlist
    },
    sum(){
      return this.$store.state.sum
    }
  },
  methods: {
    add() {
      const personId = {id: nanoid, name: this.name}
      this.$store.dispatch('add', personId)
      this.name = ''
    }
  }
}
</script>

<style>

</style>

// React/React-Cli/redux_react/09-最终版/containers/Person/index.jsx
import React, { Component } from 'react'
import {nanoid} from 'nanoid'
import {connect} from 'react-redux'
import {addPerson} from '../../redux/actions/person'

class Person extends Component {
    addPerson = () => {
        const name = this.name.value
        const age = this.age.value
        const personObj = {id:nanoid(),name,age}
        this.props.addPerson(personObj)
        this.name.value = ''
        this.age.value = ''
    }
  render() {
    return (
      <div>
          <h1>Person组件,上方组件求和为:{this.props.count}</h1>
          <input ref = { c => this.name = c} type="text" placeholder='输入名字'/>
          <input ref = { c => this.age = c} type="text" placeholder='输入年龄'/>
          <button onClick={this.addPerson}>添加</button>
          <ul>
              {
                  this.props.persons.map((person) => {
                      return (
                          <li key={person.id}>{person.name}--{person.age}</li>
                      )
                  })
              }
          </ul>
      </div>
    )
  }
}

export default connect(
    state => ({persons: state.person,count:state.count}),
    {
        addPerson
    }
)(Person)
